### ISSUE TITLE
Integration with language-markdown

### ISSUE THREAD

**Issue by burodepeper** [jonmagic/gfm-lists#2]
Hi @jonmagic,
Do you mind if I "steal" some of your work here to include in my [language-markdown](/burodepeper/language-markdown) package?

**Comment by jonmagic** [comment]
Please do :+1: Sorry for the late response, I was on vacation and away from email for 2 weeks.

**Comment by burodepeper** [comment]
Thanks! And absolutely no need to apologize for having been on vacation.

**Comment by burodepeper** [comment]
Hi there, I'm back again! : )

I've implemented _the thing_, although in a rather different way in the end. I'd appreciate it if you could take a look at my approach. Any feedback is welcome. See https://github.com/burodepeper/language-markdown/pull/45. There's a whole bunch of files involved, but I think only those in `lib/main.coffee` would be relevant, starting from line 24.
